apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-loadbalancer-service
  labels:
    app: app1-nginx
  annotations:
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v3.0/guide/service/annotations/#traffic-routing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

    # https://kubernetes-sigs.github.io/external-dns/latest/docs/tutorials/cloudflare/#deploying-an-nginx-service
    external-dns.alpha.kubernetes.io/hostname: demo301.karanimwenda.com
    external-dns.alpha.kubernetes.io/ttl: "300" #optional
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: LoadBalancer
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80