apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksdemo1 # name of the eks cluster
  region: us-east-1
fargateProfiles:
  - name: fp-app3
    selectors:
      # all workloads in the "ns-app3" k8s namespace will be scheduled onto fargate
      - namespace: ns-app3