apiVersion: v1
kind: Service
metadata:
  name: clb-restapp-service
  labels: 
    app: usermgmt-restapp
spec:
  type: LoadBalancer # default CLB
  selector:
    app: usermgmt-restapp
  ports: 
    - port: 80
      targetPort: 8095